---
title: ""
---

We invite submissions for **TU+ 11**, which will be held **in-person** at **MIT**, on **April 11–12, 2026**.

Abstracts can be submitted for 30-minute talks (20-min. talk + 10-min. Q&A), poster presentations, or both.

All abstracts will be anonymously peer-reviewed.

---

## Important Dates

- **Abstract submission deadline:** ~~December 15, 2025~~ **extended to December 22, 2025**
- **Notification of acceptance:** January 26, 2026
- **Workshop dates:** April 11–12, 2026

---

## Submission Guidelines

- Abstracts must be anonymous and not contain excessive references to the publications of the author(s) or acknowledgments to granting agencies or academic bodies.
- Abstracts should contain original research that, at the time of submission, has neither been published nor accepted for publication.
- Authors may be involved in at most **two submissions**: i) one individual abstract and one joint abstract, or ii) two joint works.
- Abstracts should not exceed **2 pages** in letter or A4 format with 1 inch margin on all sides, including examples, figures, and references.
- The font should not be smaller than 11pt.  
- Submissions should be in **PDF format**.


---

## Topics

We welcome contributions on all aspects of **linguistic research on Turkic languages**, as well as on:

- Languages in contact with Turkic
- Languages spoken in regions where Turkic languages are spoken
- Theoretical, experimental, and computational approaches

---

## How to Submit

Submissions should be made through the [**OpenReview** platform](https://openreview.net/group?id=TUplus/2026) by Monday, December 22, 2025, 11:59 pm EST.  *Make sure to create an OpenReview account at least two weeks prior to the submission deadline since it may take up to two weeks for your accounts to be verified.*

For questions, contact the organizers at: [turkicworkshop@gmail.com](mailto:turkicworkshop@gmail.com)

---

## Invited Speakers

- [**Yağmur Sağ**](https://www.yagmursag.com) (Swathmore College) — *Title TBA*
- [**Sergei Tatevosov**](http://otipl.philol.msu.ru/staff/people/tatevosov/tatevosov_eng.php) (Lomonosov Moscow State University) — *Title TBA*
