---
# title:
# subtitle:
# date:
format: html
toc: false
---

**Welcome to TU+11 at the University of Massachusetts (MIT)!** We are pleased to announce that the 11th iteration of the Workshop on Turkic and Languages in Contact with Turkic (TU+) will be hosted by MIT Linguistics. The workshop will be held at MIT, Cambridge, MA, on April 11-12, 2026 **in-person**. The abstract submissions are now open!

TU+ is an annual workshop focusing on all aspects of linguistic research on **Turkic languages**, as well as on **languages in contact with Turkic** and on **languages spoken in regions where Turkic languages are spoken**. TU+ showcases theoretically informed and data-driven work across phonology, morphology, syntax, semantics, pragmatics, psycholinguistics, neurolinguistics, historical linguistics, and computational approaches.


::: callout-note
Since 2019, papers presented at TU+ have been invited to appear in an online proceedings volume distributed by the Linguistic Society of America.
:::

---

## Code of Conduct

Please review our **Code of Conduct** before participating.
**Link:** [Code of Conduct](code-of-conduct.html)

---

## Permanent Site

For information on earlier editions, [proceedings](https://journals.linguisticsociety.org/proceedings/index.php/tu/issue/archive), and history, see the [permanent site](https://turkicworkshop.github.io/) (under construction).

---

## Invited Speakers

- [**Yağmur Sağ**](https://www.yagmursag.com) (Swathmore College) — *Title TBA*
- [**Sergei Tatevosov**](http://otipl.philol.msu.ru/staff/people/tatevosov/tatevosov_eng.php) (Lomonosov Moscow State University) — *Title TBA*


---

## Important Dates

| Milestone                        | Date                    |
|---------------------------------|-------------------------|
| Abstract submission deadline    | **December 15, 2025** - 11:59 PM EST    |
| Notification of acceptance      | **January 26, 2026**  - 11:59 PM EST    |
| Workshop                        | **April 11–12, 2026**                   |


---

## Organizing Committee

**Local Organizers (MIT)** <br>
- Bergül Soykan `bergul@mit.edu` <br>
- Cynthia Zhong `cyntz@mit.edu`  <br>
- Juan Cancel `juanc374@mit.edu` <br>
- Taieba Tawakoli `tawakoli@mit.edu` <br>
- Vladislav Orlov `vorlov@mit.edu` <br>

**Faculty Advisor** 
- [Sabine Iatridou](https://linguistics.mit.edu/user/iatridou/) (MIT)

**Program Committee**
- [Deniz Özyıldız](https://deniz.fr) (University of Stuttgart)

---

## Questions?

Email the organizers at **[turkicworkshop@gmail.com](mailto:turkicworkshop@gmail.com)**.
We’re happy to help with submissions, accessibility, and logistics.
