---
title: ""
format: html
---

Please register for TU+11 **[here](https://forms.gle/6ei1My7DdiZFdept5)** by **March 13, 2026 (Friday)** if you plan to attend the workshop in person.  


Registration for **TU+ 11 (MIT • April 11–12, 2026)** is **free**.
All participants (speakers, poster presenters, and attendees) are welcome without registration fees.

::: callout-tip
If you need an **invitation/visa letter**, please register first and then email us at **[turkicworkshop@gmail.com](mailto:turkicworkshop@gmail.com)** with your registration confirmation.
:::

<!---

## How to Register

1. Fill out the online registration form: **[Registration Form](https://forms.gle/6ei1My7DdiZFdept5)**
2. Receive a confirmation email. Save it for on-site check-in. -->

---

## Important Notes

- Registration ensures we have your information for **access control, communication, and logistics**.
- Even though it’s free, **please register as early as possible** to help us plan room capacity, catering, and materials.


---

## Accessibility

We aim to make TU+ accessible. If you have needs (step-free access, seating, captioning, dietary restrictions), indicate them in the form or email **turkicworkshop@gmail.com**. We'll follow up to accommodate.

---

## Code of Conduct

By registering, you agree to abide by the **[Code of Conduct](code-of-conduct.html)**.  

---

## Questions?

For any registration-related questions:

- Email **[turkicworkshop@gmail.com](mailto:turkicworkshop@gmail.com)**
- Join our **[Google Groups](https://forms.gle/RHkMvACuJhYSeXN97)**
- Or find more information in our posts under “Information” on the site.
